---
version: '3.7'
services:
  rosetta:
    restart: unless-stopped
    image: ewc-rosetta:latest
    container_name: rosetta
    restart: always
    volumes:
      - /data/openethereum-data/chain-data:/data
    env_file:
      - .env
    ports:
      - "8080:8080"
