version: "3.2"

services:  
  openethereum:
    image: combined:1.0.7
    container_name: openethereum
    restart: always
    env_file:
      - .env
    # networks:
    # dev:
    command:
      /start.sh openethereum
    ports:
      - "8545:8545"
      - "8546:8546"
    volumes:
      - /Users/kamilwitkowski/Coding/Personal/Apps/rosetta/new/ewc-rosetta/configOE:/parity/config:ro
  rosetta:
    image: combined:1.0.7
    container_name: rosetta
    restart: always
    env_file:
      - .env
    # networks:
    # dev:
    command:
      /start.sh rosetta

